export default {
    CHECK_EMAIL: 'CHECK_EMAIL',
    GET_COUNTRIES: 'GET_COUNTRIES',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    LOGIN: 'LOGIN',
    GENERATE_PIN: 'GENERATE_PIN',
    VERIFY_PIN: 'VERIFY_PIN',
    GENERATE_PASSWORD: 'GENERATE_PASSWORD',
    CREATE_QUIZ: 'CREATE_QUIZ',
    FINISH_QUIZ: 'FINISH_QUIZ',
    GET_PAGES: 'GET_PAGES',
    GET_USER_DATA: 'GET_USER_DATA',
    EDIT_USER_DATA: 'EDIT_USER_DATA',
    GET_USER_STATISTICS: 'GET_USER_STATISTICS',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT'
} as const
