export default Object.freeze({
  logo: require('../assets/logo.png'),
  logo_white: require('../assets/logo-white.png'),
  bgintro: require('../assets/sign-up-bg.png'),
  bgfood: require('../assets/bg-food.png'),
  onboarding: require('../assets/onboarding-bg.png'),
  waist_measurement_tip: require('../assets/waist-measurement-tip.png'),
  welcome_dark: require('../assets/welcome-bg-dark.png'),
  welcome_light: require('../assets/welcome-bg-light.png'),
  dashed_line: require('../assets/dashed-line.png'),

  phone_unlocked: require('../assets/phone-unlocked.png'),
  phone_sms: require('../assets/phone-sms.png'),

  grocery_amazon: require('../assets/grocery_amazon.png'),
  grocery_amazon_dark: require('../assets/grocery_amazon_dark.png'),
  grocery_amazon_loader: require('../assets/grocery_amazon_loader.png'),
  grocery_amazon_loader_dark: require('../assets/grocery_amazon_loader_dark.png'),

  grocery_kroger: require('../assets/grocery_kroger.png'),
  grocery_kroger_dark: require('../assets/grocery_kroger_dark.png'),
  grocery_kroger_loader: require('../assets/grocery_kroger_loader.png'),
  grocery_kroger_loader_dark: require('../assets/grocery_kroger_loader_dark.png'),

  grocery_instakart: require('../assets/grocery_instakart.png'),
  grocery_instakart_dark: require('../assets/grocery_instakart_dark.png'),
  grocery_instakart_loader: require('../assets/grocery_instakart_loader.png'),
  grocery_instakart_loader_dark: require('../assets/grocery_instakart_loader_dark.png'),

  marketing: {
    page1: require('../assets/marketing1.png'),
    page2: require('../assets/marketing2.png'),
    page3: require('../assets/marketing3.png')
  },

  icon: {
    subscription_delivery: require('../assets/icons/subscription_delivery.png'),
    subscription_batter: require('../assets/icons/subscription_batter.png'),
    subscription_on_time: require('../assets/icons/subscription_on-time.png'),
    energy: require('../assets/icons/energy.png'),
    performance: require('../assets/icons/performance.png'),
    footprint: require('../assets/icons/footprint.png'),
    health: require('../assets/icons/health.png'),
    immunity: require('../assets/icons/immunity.png'),
    inflammation: require('../assets/icons/inflammation.png'),
    energy_white: require('../assets/icons/energy_white.png'),
    performance_white: require('../assets/icons/performance_white.png'),
    footprint_white: require('../assets/icons/footprint_white.png'),
    health_white: require('../assets/icons/health_white.png'),
    immunity_white: require('../assets/icons/immunity_white.png'),
    inflammation_white: require('../assets/icons/inflammation_white.png'),
    trophy: require('../assets/icons/trophy.png'),
    trophy_white: require('../assets/icons/trophy_white.png'),
    image: require('../assets/icons/image.png'),
    shop: require('../assets/icons/shop.png'),
    scribble: require('../assets/icons/scribble.png'),
    clipboard: require('../assets/icons/clipboard.png'),
    flag: require('../assets/icons/flag.png'),
    flag_white: require('../assets/icons/flag_white.png'),
    flag_gray: require('../assets/icons/flag_gray.png'),
    flag_gray_white: require('../assets/icons/flag_white.png'),
    star: require('../assets/icons/star.png'),
    star_white: require('../assets/icons/star_white.png'),
    trophy_small: require('../assets/icons/trophy_small.png'),
    trophy_small_white: require('../assets/icons/trophy_small_white.png'),
    meal: require('../assets/icons/meal.png'),
    meal_white: require('../assets/icons/meal_white.png'),
    double_check: require('../assets/icons/double_check.png'),
    double_check_white: require('../assets/icons/double_check_white.png'),
    candy: require('../assets/icons/candy.png'),
    flame: require('../assets/icons/flame.png'),
    flame_white: require('../assets/icons/flame_white.png'),
    fork_and_knife: require('../assets/icons/fork_and_knife.png'),
    fork_and_knife_white: require('../assets/icons/fork_and_knife_white.png'),
    block: require('../assets/icons/block.png'),
    block_white: require('../assets/icons/block_white.png'),
    kitchen_tools: require('../assets/icons/kitchen_tools.png'),
    kitchen_tools_white: require('../assets/icons/kitchen_tools_white.png'),
    heart: require('../assets/icons/heart.png'),
    heart_white: require('../assets/icons/heart_white.png'),
    bookmark: require('../assets/icons/bookmark.png'), // done
    bookmark_white: require('../assets/icons/bookmark_white.png'), // done
    bookmark_active: require('../assets/icons/bookmark_active.png'), // done
    log_dark: require('../assets/icons/log_dark.png'),
    log_mark_complete: require('../assets/icons/log_mark_complete.png'),
    log_mark_complete_white: require('../assets/icons/log_mark_complete_white.png'),
    make_dishqou_better: require('../assets/icons/make_dishqou_better.png'),
    make_dishqou_better_white: require('../assets/icons/make_dishqou_better_white.png'),
    number_of_servings: require('../assets/icons/number_of_servings.png'), // done
    repeat_meal: require('../assets/icons/repeat_meal.png'),
    repeat_meal_white: require('../assets/icons/repeat_meal_white.png'),
    replace_meal: require('../assets/icons/replace_meal.png'),
    replace_meal_white: require('../assets/icons/replace_meal_white.png'),
    schedule_meal: require('../assets/icons/schedule_meal.png'),
    schedule_meal_white: require('../assets/icons/schedule_meal_white.png'),
    skip_meal: require('../assets/icons/skip_meal.png'),
    skip_meal_white: require('../assets/icons/skip_meal_white.png'),
    time_to_prepare: require('../assets/icons/time_to_prepare.png'), // done
    challenge: require('../assets/icons/challenge.png'),
    challenge_gray: require('../assets/icons/challenge_gray.png'),
    challenge_white: require('../assets/icons/challenge_white.png'),
    my_meal: require('../assets/icons/my_meal.png'),
    my_meal_gray: require('../assets/icons/my_meal_gray.png'),
    my_meal_white: require('../assets/icons/my_meal_white.png'),
    profile: require('../assets/icons/profile.png'),
    profile_gray: require('../assets/icons/profile_gray.png'),
    profile_white: require('../assets/icons/profile_white.png'),
    rewards: require('../assets/icons/rewards.png'),
    rewards_gray: require('../assets/icons/rewards_gray.png'),
    rewards_white: require('../assets/icons/rewards_white.png'),
    today: require('../assets/icons/today.png'),
    today_gray: require('../assets/icons/today_gray.png'),
    today_white: require('../assets/icons/today_white.png'),
    check_circle: require('../assets/icons/check-circle.png'),
    add_guest: require('../assets/icons/add_guest.png'),
    add_guest_white: require('../assets/icons/add_guest_white.png'),
    remove_guest: require('../assets/icons/remove_guest.png'),
    remove_guest_white: require('../assets/icons/remove_guest_white.png'),
    intercom: require('../assets/intercom.png'),
    expand_down: require('../assets/icons/expand_down.png'),
    complete_on_boarding: require('../assets/icons/complete_on_boarding.png'),
    complete_on_boarding_white: require('../assets/icons/complete_on_boarding_white.png'),
    add: require('../assets/icons/add.png'),
    remove: require('../assets/icons/remove.png'),
    batch_and_repeat: require('../assets/icons/batch_and_repeat.png'),
    log_meal: require('../assets/icons/log_meal.png'),
    set_schedule: require('../assets/icons/set_schedule.png'),
    meal_skip: require('../assets/icons/meal_skip.png'),
    meal_replace: require('../assets/icons/meal_replace.png'),
    ingredients_goal_all: require('../assets/icons/ingredients_goal_all.png'),
    ingredients_goal_all_white: require('../assets/icons/ingredients_goal_all_white.png'),
    ingredients_goal_savemoney_white: require('../assets/icons/ingredients_goal_savemoney_white.png'),
    ingredients_goal_savemoney: require('../assets/icons/ingredients_goal_savemoney.png'),
    remove_white: require('../assets/icons/remove_white.png'),
    household_member: require('../assets/icons/household_member.png'),
    household_member_white: require('../assets/icons/household_member_white.png'),
    play_video: require('../assets/icons/play_video.png'),
    decrease_white: require('../assets/icons/decrease_white.png'),
    decrease: require('../assets/icons/decrease.png'),
    camera_icon: require('../assets/icons/camera_icon.png'),
    play_white: require('../assets/icons/decrease_white.png'),
    play: require('../assets/icons/decrease.png'),
    first_recipe: require('../assets/icons/first_recipe.png'),
    first_recipe_white: require('../assets/icons/first_recipe_white.png'),
    lock: require('../assets/icons/lock.png'),
  },

  milestone: {
    joined: require('../assets/milestone_joined.png'),
    unjoined: require('../assets/milestone_unjoined.png')
  },

  badge: {
    star: require('../assets/star_badge.png'),
    star_bronze: require('../assets/star_badge_bronze.png'),
    star_silver: require('../assets/star_badge_silver.png'),
    star_gold: require('../assets/star_badge_gold.png')
  },

  double_smiley: require('../assets/double_smiley.png'),
  heart_thumbsup: require('../assets/heart_thumbsup.png'),
  people_share: require('../assets/people_share.png'),
  megaphone: require('../assets/megaphone.png'),
  invite_a_friend: require('../assets/invite_a_friend.png'),
  wallet: require('../assets/wallet.png'),

  rewards_masthead: require('../assets/rewards_masthead.jpg'),
  mealcard_gradient: require('../assets/mealcard_gradient.png'),
  discover_fb: require('../assets/discover_fb.png'),
  discover_insta: require('../assets/discover_insta.png'),
  refer_and_earn: require('../assets/icons/refer_and_earn.png'),
  refer_and_earn_white: require('../assets/icons/refer_and_earn_white.png'),
  digitalPantryIntro: require('../assets/digital_pantry_intro.png'),

  subscription_image: require('../assets/subscription_image.png'),

  login: {
    apple: require('../assets/login-apple.png'),
    fb: require('../assets/login-fb.png'),
    google: require('../assets/login-google.png'),
    email: require('../assets/login-email.png')
  },

  default: {
    avatar: require('../assets/default_avatar.jpeg')
  },

  empty: {
    grocery: require('../assets/empty_grocery.png'),
    meal: require('../assets/empty_meal.png')
  },

  rating: {
    bad: require('../assets/icons/rating_bad.png'),
    not_bad: require('../assets/icons/rating_not_bad.png'),
    good: require('../assets/icons/rating_good.png'),
    very_good:require ('../assets/icons/rating_very_good.png'),
    exellent: require('../assets/icons/rating_exellent.png'),
  }
});
