// Generated by https://quicktype.io

export interface IStatistics {
    code: string
    message: string
    data: Data
}

export interface Data {
    total_questions: number
    success_rate: string
    total_quizzes: number
    rang: number
    category_1: string
    category_2: string
    category_3: string
    category_4: string
    category_5: string
    category_6: string
    category_7: string
}
