// Generated by https://quicktype.io

export interface IUser {
    city: string
    country: number
    country_name: string
    email: string
    name: string
    phone: string
    username: string
}
